common:
  work_dir: "test"
  image_shape:
    height: 128
    width: 128

noise_scheduler:
  num_timesteps: 1000
  beta_start: 1.0e-4
  beta_end: 0.02
  noise_steps: 10

cnn_model:
  filters: [32, 64, 128]
  kernel_sizes: [5, 5, 5]
  model_filename: "model.keras"
  checkpoint_filename: "checkpoint.keras"
  num_epochs: 1000
  learning_rate: 1.0e-4
  resume: false
  from_checkpoint: true